url:
  base-url: 192.168.2.213

spring:
  cloud:
    nacos:
      discovery:
        #注册中心地址
        server-addr: ${url.base-url}:8848
      config:
        #配置中心地址
        server-addr: ${url.base-url}:8848
  datasource:
    url: jdbc:mysql://${url.base-url}:3306/alibaba?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

seata:
  registry:
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    nacos:
      server-addr: ${spring.cloud.nacos.config.server-addr}
